### ISSUE TITLE
kibana LDAP authent and HTTP Basic authentication

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfadmin#245]
If we use LDAP to authenticate to kibana, we are prompted anyway with the HTTP Basic authentication:
![image](https://user-images.githubusercontent.com/38913120/220142764-017423ec-6059-48a9-8bf7-ddb5697d6c44.png)

in nginx config maybe this part must be ignored:
```
auth_basic "Restricted";
auth_basic_user_file /home/mfadmin/tmp/kibana.passwd;
```
if LDAP is activated.

So in `https://github.com/metwork-framework/mfadmin/blob/master/config/nginx.conf` we should try this :
```
location /kibana/ {
    {% if MFADMIN_LDAP_FLAG == "1" %}
    {{ macros.common_ldap() }}
    {% else %}
    auth_basic "Restricted";
    auth_basic_user_file {{MFMODULE_RUNTIME_HOME}}/tmp/kibana.passwd;
    {% endif %}
    proxy_pass http://127.0.0.1:{{MFADMIN_KIBANA_HTTP_PORT}}/;
}
```

**Comment by thebaptiste** [comment]
Did you try this fix ?

**Comment by matthieumarrast** [comment]
yes, I just tested it. It's OK. I'm doing the PR.
