### ISSUE TITLE
move code of kibana web interface from ~/tmp/ to ~/var/

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfadmin#260]
The code of kibana web application is stored under `/home/mfadmin/tmp/kibana`

But the `~/tmp/` folder is a temporary directory, so **it can be removed by a purge process** (cf. crontab).

The command executing Kibana (with NodeJS) is : `/home/mfadmin/tmp/kibana/bin/../node/bin/node --no-warnings /home/mfadmin/tmp/kibana/bin/../src/cli --config /home/mfadmin/tmp/kibana/config/kibana.yml` as you can see with `ps` command.

Study the way to **move it to `~/var/`**, be careful of symbolic links.

N.B: I'm also surprised to see that config `/home/mfadmin/tmp/kibana/config/kibana.yml` is used instead of `/home/mfadmin/tmp/config_auto/kibana/kibana.yml`

**Comment by thebaptiste** [comment]
Could you test replacing these lines in crontab : 
```0 2 * * * /home/baptiste/mfadmin/build/bin/cronwrap.sh --lock --timeout=3600 --log-capture-to=NULL -- 'find /home/baptiste/metwork/mfadmin/tmp -type f -not -path "/home/baptiste/metwork/mfadmin/tmp/config_auto/*" -mtime +2 -delete'
30 2 * * * /home/baptiste/mfadmin/build/bin/cronwrap.sh --lock --timeout=3600 --log-capture-to=NULL -- 'find /home/baptiste/metwork/mfadmin/tmp -type d -not -path "/home/baptiste/metwork/mfadmin/tmp/config_auto" -mtime +2 -exec rmdir {} \;'```
by these ones : 
```0 2 * * * /home/baptiste/mfadmin/build/bin/cronwrap.sh --lock --timeout=3600 --log-capture-to=NULL -- 'find /home/baptiste/metwork/mfadmin/tmp -type f -not -path "/home/baptiste/metwork/mfadmin/tmp/config_auto/*" -not -path "/home/baptiste/metwork/mfadmin/tmp/kibana/*" -mtime +2 -delete'
30 2 * * * /home/baptiste/mfadmin/build/bin/cronwrap.sh --lock --timeout=3600 --log-capture-to=NULL -- 'find /home/baptiste/metwork/mfadmin/tmp -type d -not -path "/home/baptiste/metwork/mfadmin/tmp/config_auto" -not -path "/home/baptiste/metwork/mfadmin/tmp/kibana/*" -mtime +2 -exec rmdir {} \;'``

**Comment by thebaptiste** [comment]
If it's ok it's easy to change the template `crontab` for MFADMIN in mfext
